set_stored_traces:
  name: Set stored traces
  description: Updates the stored_traces value in your YAML files and reloads the configurations.
  target:
    entity:
      domain:
        - automation
        - script
  fields:
    traces:
      name: Target number of traces
      description: The number of traces to store (Home Assistant defaults to 5).
      example: 50
      default: 50
      selector:
        number:
          min: 5
          max: 100
          mode: box